// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Reflow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidReflowPackageString = "8b12a0ce-bbf4-4f0a-a590-62f10160a171";
        public const string guidReflowPackageCmdSetString = "c0e01b22-96f5-4b93-ab8b-4e500cb2db5d";
        public const string guidImagesString = "904a541f-0c39-4857-9a6c-e84bb530a51a";
        public static Guid guidReflowPackage = new Guid(guidReflowPackageString);
        public static Guid guidReflowPackageCmdSet = new Guid(guidReflowPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidReflow = 0x0100;
        public const int bmpIcon = 0x0001;
    }
}
