// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Reflow
{
    static class Vsix
    {
        public const string Id = "Reflow.2af72dbc-b8ef-438a-bc03-922e5acf446c";
        public const string Name = "Reflow";
        public const string Description = @"Formats the current selection to have lines no longer than 80 characters. If nothing is selected, the current line is reflowed.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Klaus Hartke";
        public const string Tags = "format, reflow";
    }
}
